### PR TITLE
docs: add 0.15.x docs section

### PR DESCRIPTION
**Pull request by craicoverflow**
Depends on https://github.com/aerogear/graphback/pull/1786

### CODE REVIEW

**Comment by machi1990** [comment]
Should we bring https://github.com/aerogear/graphback/pull/1785 in too?

**Comment by craicoverflow** [comment]
Yeah sure, let's get that reviewed and merged first

**Comment by craicoverflow** [comment]
#1785 has been included in this now @machi1990

**Comment by machi1990** [comment]
> #1785 has been included in this now @machi1990

Cool, looking now.

**Pull request merged**
