### PR TITLE
ESLint migration.

### LINKED ISSUE #642: Migrate from tslint to eslint

### PR DESCRIPTION
**Pull request by cecobask**
Only package.json files were modified + added eslint configuration. /example dir was auto-generated.
fixes #642

### CODE REVIEW

**Comment by wtrocki** [comment]
We do not commit example dir. It is used for demos. I will add info to contribution guide

**Comment by wtrocki** [comment]
Thank you so much for contribution. This is indeed all that was needed. I will rebase it later

**Comment by wtrocki** [comment]
Hi

Missundestanding on my side. We cannot remove examples or gitignore them. We use it for demos, but we do not commit them. Generally good rule of thumb is to not commit any code that is not related to motivation of the PR. 

How to resolve this?
Lets drop last commit completely and then 
`git reset --soft head~1` will help you to reject examples codebase from first commit.

Sorry for amount of hassle you are experiencing on this

**Comment by wtrocki** [comment]
Going to merge this during the week

**Comment by craicoverflow** [comment]
Merged in https://github.com/aerogear/graphback/pull/717

**Pull request closed without merging**
