### PR TITLE
ESLint migration

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Comment by wtrocki** [comment]
@cecobask I have a problem with merging these changes (this is on me) as we have made some significant changes in the codebase on feature branch that is not merged to master. However I would love to see us using eslint rules etc. 

Do you think it will be possible to split contribution into 2 phases:

- Contribute just eslint rules file and package name
I would recomend to copy paste files from:
https://github.com/aerogear/offix/pull/328/files

This will be merged into the feature branch where we will try to fix those issues by team and adjust them.

**Comment by cecobask** [comment]
I'm on it

**Comment by wtrocki** [comment]
To make it clear. Let's just not change the codebase. We will merge into feature branch that is failing anyway and work on fixes there

**Comment by cecobask** [comment]
Opened a pull request #677 with ESLint working. The tests are also passing now. But I haven't touched on the codebase, as requested. That's the reason linting on CI is failing.

**Pull request closed without merging**
