### PR TITLE
chore: update graphql version

### PR DESCRIPTION
**Pull request by craicoverflow**
Effort to make Graphback compatible with GraphQL.js v15

### CODE REVIEW

**Comment by wtrocki** [comment]
I will watch this! Awesome work!

**Comment by craicoverflow** [comment]
Seeing this locally for all packages:
```
warning " > @graphback/codegen-client@0.14.0-alpha4" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
warning " > @graphback/codegen-offix@0.14.0-alpha4" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
...
```

But I believe this is a false positive due to Yarn workspaces hoisting dependencies.

**Comment by craicoverflow** [comment]
fyi this looks to be working

Want to do some more verification tomorrow and add a proper PR description, but feel free to review now!

**Comment by wtrocki** [comment]
Verification would be to downgrade graphql to v14 and see if that still works. 
All changes seems to look ok for me!

**Comment by craicoverflow** [comment]
> Verification would be to downgrade graphql to v14 and see if that still works.
> All changes seems to look ok for me!

Yeah I had briefly tried that but want to do it outside of the monorepo to be sure.

**Comment by wtrocki** [comment]
Including into release

**Comment by machi1990** [comment]
Good job @craicoverflow

**Pull request merged**
