### PR TITLE
fix(templates): replaced _id with id

### LINKED ISSUE #2249: apollo-fullstack-react-postgres-ts template project error
* **Module**:
* **Version**:
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

Straight out of the box, using 'apollo-fullstack-react-postgres-ts' project template, you can't create Notes using the example Create Note form, since datamodel.graphql uses "_id: ID!" 

However according to 'isAutoPrimaryKey' an auto primary key can only be called "_id" if its GraphbackObjectID type, other it needs to be "id" if its "ID".

Modifying the schema to use "id: ID!" and regenerating fixes the issue.

For reference, upon the 'Add Note' button click, you get
'Unhandled Rejection (Error): Response not successful: Received status code 400'

and the stack trace in the Response, in Web Developer is
{
	"stacktrace": [
		"GraphQLError: Variable \"$input\" got invalid value { title: \"fdujifdhiu\", description: \"985478975498745\" }; Field \"_id\" of required type \"ID!\" was not provided.",
		"    at /home/andy/src/fas-app/node_modules/graphql/execution/values.js:116:15",
		"    at coerceInputValueImpl (/home/andy/src/fas-app/node_modules/graphql/utilities/coerceInputValue.js:100:11)",
		"    at coerceInputValueImpl (/home/andy/src/fas-app/node_modules/graphql/utilities/coerceInputValue.js:56:14)",
		"    at coerceInputValue (/home/andy/src/fas-app/node_modules/graphql/utilities/coerceInputValue.js:39:10)",
		"    at _loop (/home/andy/src/fas-app/node_modules/graphql/execution/values.js:109:69)",
		"    at coerceVariableValues (/home/andy/src/fas-app/node_modules/graphql/execution/values.js:121:16)",
		"    at getVariableValues (/home/andy/src/fas-app/node_modules/graphql/execution/values.js:50:19)",
		"    at buildExecutionContext (/home/andy/src/fas-app/node_modules/graphql/execution/execute.js:206:61)",
		"    at executeImpl (/home/andy/src/fas-app/node_modules/graphql/execution/execute.js:104:20)",
		"    at Object.execute (/home/andy/src/fas-app/node_modules/graphql/execution/execute.js:63:35)"
	]
}

Install log was:::

andy@andy-ThinkPad-X1-Carbon-4th:~/src$ npx create-graphback fas-app
npx: installed 134 in 6.341s
   ____                          _       _                      _    
  / ___|  _ __    __ _   _ __   | |__   | |__     __ _    ___  | | __
 | |  _  | '__|  / _` | | '_ \  | '_ \  | '_ \   / _` |  / __| | |/ /
 | |_| | | |    | (_| | | |_) | | | | | | |_) | | (_| | | (__  |   < 
  \____| |_|     \__,_| | .__/  |_| |_| |_.__/   \__,_|  \___| |_|\_\
                        |_|                                          
create-graphback can create your app from following templates:
  
apollo-fullstack-react-postgres-ts: 
Apollo GraphQL Server connecting to Postgres database and React client using TypeScript

apollo-fullstack-react-mongo-ts: 
Apollo GraphQL Server connecting to Mongo database and React client using TypeScript

apollo-mongo-server-ts: 
Apollo GraphQL Server connecting to Mongo database using TypeScript

apollo-mongo-datasync-server-ts: 
Apollo GraphQL Server connecting to Mongo database using TypeScript. Contains Data Synchronization features.

apollo-postgres-server-ts: 
Apollo GraphQL Server connecting to Postgres database using TypeScript

[PREVIEW] apollo-mongo-apache-kafka-server-ts: 
Apollo GraphQL server connecting to MongoDB database with Apache Kafka for subscriptions. This is a preview template - we are continuing to enhance it - we welcome your feedback.
  
? Choose a template to bootstrap apollo-fullstack-react-postgres-ts

Bootstraping graphql server 💫 ✨
✔ Downloading starter from https://api.github.com/repos/aerogear/graphback/tarball/templates-1.0.0
✔ Extracting content to /home/andy/src/fas-app/client
✔ Downloading starter from https://api.github.com/repos/aerogear/graphback/tarball/templates-1.0.0
✔ Extracting content to /home/andy/src/fas-app/

GraphQL server successfully bootstrapped 🚀

Next Steps:
1. Change directory into project folder - cd fas-app
2. Follow template README.md to start server

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Fixes #2249 

## Types of changes

What types of changes does your code introduce to Graphback?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please specify)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aerogear/graphback/blob/master/CONTRIBUTING.md) document.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Verification

https://user-images.githubusercontent.com/56963264/106379742-23d04380-63d4-11eb-8751-7888672d478d.mp4

## Further comments

After discussion, it was decided to have the client app working with Postgres only and not mongo since client side queries are still there for testing if needed. To make the client template work with Postgres I made the following two changes:

1.  Replaced `_id` with `id` in postgres template's [datamodel.graphql](https://github.com/aerogear/graphback/blob/master/templates/ts-apollo-postgres-backend/model/datamodel.graphql) file. Ran `yarn generate` to update the required files.
2. Replaced all instances of `_id` with `id` in the client template.

Please let me know in case something needs to be changed. Thanks!

### CODE REVIEW

**Comment by craicoverflow** [comment]
image

The React MongoDB fullstack template would need to be removed.

**Comment by craicoverflow** [comment]
When making changes which affect templates like this verification steps should include using `create-graphback` to create a new template. I found a bug (https://github.com/aerogear/graphback/pull/2261) while doing this. The bug was not caused by this PR, but existed already.

**Comment by RinkiyaKeDad** [comment]
Thanks for the feedback @craicoverflow. I started verifying using `create-graphback` but faced a problem.
1. I first ran `npm run build` in the `create-graphback` directory and then ran `node dist/index.js testtt` to test the changes.
2. I too first faced the bug you mentioned (#2261) and made the change you had made.
3. When I tried again after fixing that I got this error:
```
TypeError: request_1.default is not a function
    at /home/arsh/OpenSource/graphback/packages/create-graphback/dist/init/starterTemplates.js:145:30
    at new Promise (<anonymous>)
    at /home/arsh/OpenSource/graphback/packages/create-graphback/dist/init/starterTemplates.js:144:15
    at Generator.next (<anonymous>)
    at /home/arsh/OpenSource/graphback/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/arsh/OpenSource/graphback/node_modules/tslib/tslib.js:110:16)
    at downloadRepository (/home/arsh/OpenSource/graphback/packages/create-graphback/dist/init/starterTemplates.js:138:20)
    at Object.<anonymous> (/home/arsh/OpenSource/graphback/packages/create-graphback/dist/init/starterTemplates.js:185:32)
    at Generator.next (<anonymous>)
```

Is this because of the way I'm trying to run `create-graphback` because I got neither of these errors earlier when I used `npx create-graphback my-awesome-project`?

**Comment by RinkiyaKeDad** [comment]
@wtrocki please have a look :)

**Comment by craicoverflow** [comment]
I think I fixed the issue you mentioned above in https://github.com/aerogear/graphback/pull/2261

**Comment by RinkiyaKeDad** [comment]
Hi @craicoverflow! You fixed `TypeError: parse_github_url_1.default is not a function` in #2261 but I faced a different error `TypeError: request_1.default is not a function`. Also, I just noticed that my format on save introduced a lot of unwanted changes so I think it's best I close this PR and make another one that way I'll have the commit you made to fix #2261 in my code too.

**Pull request closed without merging**
