### PR TITLE
fix: remove id indexes from mongo

### PR DESCRIPTION
**Pull request by ssd71**
Towards #1547

### CODE REVIEW

**Comment by wtrocki** [comment]
Build failing

**Comment by wtrocki** [comment]
`can create default indexes` needs to be changed as well. Minor fix

**Comment by ssd71** [comment]
The tests are still failing it seems, same as before, it's downloading Mongo memory server:
Screenshot_2020-06-25 build (5345) - aerogear graphback

**Comment by wtrocki** [comment]
We just have removed stuff so this is really strange. 
On long run we need to think if there is Mongo wrapper that do not require Mongo binary.

**Comment by wtrocki** [comment]
Also see: https://github.com/aerogear/graphback/pull/1567/files

**Comment by craicoverflow** [comment]
So strange, this is a very intermittent issue that I was seeing for months when running tests locally, but it all of a sudden went away a couple of weeks ago.

**Comment by ssd71** [comment]
How about this:
https://github.com/nodkz/mongodb-memory-server#mongodb-memory-server-global
> Auto-downloads the latest mongod binary on npm install to: `%HOME%/.cache/mongodb-binaries` / `~/.cache/mongodb-binaries.`

I am not seeing this error locally, perhaps because I have copied the mongo binary to the packages' node_modules

**Comment by ssd71** [comment]
I think this error occurs because mongo-memory-server cannot find the mongod binary in the node_modules of the package folder, because it is in the root node_modules

**Comment by ssd71** [comment]
Still doesn't explain why we weren't seeing it for a few weeks, and it just keeps popping up every now and then

**Comment by ssd71** [comment]
image

Please verify @wtrocki @machi1990 @craicoverflow

**Comment by wtrocki** [comment]
@ssd71 I see changes but I have not way to verify it without sample app. Let's merge and invest time into integration tests and datasync sample. 

This works for vanilla mongo app now.

**Comment by wtrocki** [comment]
Packages should be cached and this problem should never happen on CI/CD

**Comment by ssd71** [comment]
> @ssd71 I see changes but I have not way to verify it without sample app. Let's merge and invest time into integration tests and datasync sample.

+9000 to DataSync Sample

**Pull request merged**
