### PR TITLE
Paging support for find by Work In Progress Closes #834

### LINKED ISSUE #834: Add limit and offset to findBy
Our crud interfaces have limit and offset for the findAll method. 
We missing that on findBy method

### PR DESCRIPTION
**Pull request by Eunovo**

### CODE REVIEW

**Comment by Eunovo** [comment]
This is my **Work in Progress** PR for Issue #834

**Comment by wtrocki** [comment]
Really good job! Thanks for refactoring

**Comment by Eunovo** [comment]
Alright

**Comment by wtrocki** [comment]
what is your nickname on chat? did you joined it?

**Comment by Eunovo** [comment]
I'm using my full name, Usiwoma Oghenovo

**Comment by Eunovo** [comment]
@wtrocki Am I missing anything?

**Comment by wtrocki** [comment]
This looks really good. I will try to review and test it early tomorrow. Thank you so much for your contribution

**Comment by wtrocki** [comment]
This looks and works as it should! Thank you so much for amazing contribution to graphback!

**Pull request merged**
