### PR TITLE
Add Pagination support

### PR DESCRIPTION
**Pull request by binayakbehera999**
Added a pagination function to fetch paginated data using the paginate interface which contains the offset and limit values

### CODE REVIEW

**Comment by wtrocki** [comment]
Thank you so much for contribution.
Would i be possible to clean changes that are not relevant to the pagination? Change looks great but we will need to cover it by unit test

PS:;We use conventional commits for commiting changes

**Comment by binayakbehera999** [comment]
Thanks for the feedback. Yeah you can clean the changes that aren't relevant. Will definitely use the conventional commits from next time.

**Comment by wtrocki** [comment]
Generally, this change opens many possibilities in the entire ecosystem and we can use it for discussion on how things can be done. I'm worried is that with such an amount of irrelevant changes it will be hard to get things and help you with the implementation of the pagination. Would it be possible to apply my suggestions on this PR or even create new one?

On the technical side. I would recomend focus on better names for the methods and interfaces. Paginate is very generic etc. We might also need pagination with filtering (coresponding to `findBy` method)

**Comment by wtrocki** [comment]
@binayakbehera999 closing as outdated. Feel free to create new PR with the fixes.

**Pull request closed without merging**
