### PR TITLE
feat: change public API methods in `graphql-migrations`

### PR DESCRIPTION
**Pull request by craicoverflow**
https://github.com/aerogear/graphback/issues/552

Change the public API methods in `graphql-migrations`.

- migrate: migrateDB
- runGraphqlMigration: migrateProduction

### CODE REVIEW

**Comment by wtrocki** [comment]
WDYT?

migrateDB -> dev, default
migrateDBUsingSchema -> production/controled env

**Comment by craicoverflow** [comment]
> migrateDBUsingSchema

Are you suggesting just a rename here?

I don't fully understand the choice of `migrateDBUsingSchema`. They both accept the schemaText as the schema source.

**Comment by wtrocki** [comment]
Also `migrateProduction` is not documented. Having a short chapter will be beneficial?
We had some docs before

**Comment by wtrocki** [comment]
migrateProduction it is not reflectin what this is happening.
MigrateProduction is not a destructive way to migrate changes with audit log that uses schema as source and ignores db. migrateDB compares db and schema

**Comment by craicoverflow** [comment]
> migrateProduction it is not reflectin what this is happening.
> MigrateProduction is not a destructive way to migrate changes with audit log that uses schema as source and ignores db. migrateDB compares db and schema

Yeah I see what you mean now.

**Pull request merged**
