### PR TITLE
docs(website): added v1 docs to website

### PR DESCRIPTION
**Pull request by craicoverflow**
1. This PR publishes the docs for version 1 of Graphback.
2. Also removes older Graphback versions no longer supported (<14.0) (closing #2066)

### CODE REVIEW

**Comment by craicoverflow** [comment]
@machi1990 @wtrocki I am happy to go with a stable release of Graphback once this is merged. Suit you?

**Comment by wtrocki** [comment]
My browser crashing when I try to approve it so.. 

Approved! :D

**Comment by wtrocki** [comment]
And yes. Stable release is good

**Comment by craicoverflow** [comment]
> My browser crashing when I try to approve it so..

> Approved! :D

Luckily our prodigy @machi1990 created a GitHub Action to aid verification :wink: 

Thanks! I will wait for official approval before merge.

**Comment by machi1990** [comment]
> > My browser crashing when I try to approve it so..
> 
> > Approved! :D
> 
> Luckily our prodigy @machi1990 created a GitHub Action to aid verification 
> 
> Thanks! I will wait for official approval before merge.

Verifying this now as we speak.

**Comment by machi1990** [comment]
I am seeing these warnings:

```log
Docs markdown link couldn't be resolved: (../api/core/classes/_runtime_crudservice_.crudservice.md) in /graphback/website/versioned_docs/version-1.0/resolvers/custom-resolvers.md for version 1.0
Docs markdown link couldn't be resolved: (../overview.md) in /graphback/website/versioned_docs/version-1.0/plugins/creating-your-own-plugin.md for version 1.0
Docs markdown link couldn't be resolved: (../api/core/classes/_runtime_crudservice_.crudservice.md) in /graphback/docs/resolvers/custom-resolvers.md for version current
Docs markdown link couldn't be resolved: (../overview.md) in /graphback/docs/plugins/creating-your-own-plugin.md for version current
Docs markdown link couldn't be resolved: (../api/core/classes/_runtime_crudservice_.crudservice.md) in /graphback/website/versioned_docs/version-0.16.x/resolvers/custom-resolvers.md for version 0.16.x
```
Looks unrelated but looks like broken links. We can get them fixed in this PR or a followup PR as you prefer. 

Nitpick: Should the version `1.0` be `1.0.0` so that it matches the previous releases?

**Review by machi1990 — APPROVED** [review]
Added comments which can be fixed in this PR or followup PR. Really good change and happy with 1.0 release. Thanks <3

**Comment by craicoverflow** [comment]
> Nitpick: Should the version 1.0 be 1.0.0 so that it matches the previous releases?

I removed it because:

a) The patch version will never be shown in the releases anyway as they will not have any features
b) Having an x like 1.0.x, 1.1.x seems largely redundant since it will never change I didn't see any point in keeping it.

**Pull request merged**
