### PR TITLE
fix(fastify-template): switching to apollo-server-fastify

### LINKED ISSUE #2174: Subscriptions not working in GraphiQL Playground with Fastify
// TODO

* **Module**:
* **Version**:
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Fixes #2174 

## Types of changes

What types of changes does your code introduce to Graphback?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please specify)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aerogear/graphback/blob/master/CONTRIBUTING.md) document.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Verification
Subscriptions are now working in the Fastify template. 
subsWorking

## Further comments

There was a slight problem while fixing this. The latest stable release of [apollo-server-fastify](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-fastify) is `2.19.1` which has not been configured to [work properly with Fastify v3](https://stackoverflow.com/questions/63072227/apollo-graphql-with-fastify). [An early alpha](https://github.com/apollographql/apollo-server/pull/4356#issuecomment-677515901) does exist but I am not sure if that would work and what separate issues that might bring along with it. Since I shifted to Fastify v2 I also had to shift to v3 of `fastify-cors` since v4 only supports Fastify v3.

> Will update the README to reflect that we're using apollo-server-fastify instead of mercurius once we can confirm that the issue is now fixed.

### CODE REVIEW

**Comment by wtrocki** [comment]
In my queue. Will take look into this!

**Comment by RinkiyaKeDad** [comment]
@wtrocki - please review this one too

**Comment by wtrocki** [comment]
Sure. Needs rebase

**Comment by wtrocki** [comment]
Let's merge https://github.com/aerogear/graphback/pull/2269 then we will rebase this one and verify.

**Comment by wtrocki** [comment]
Using Apollo-server fastify which is not well maintained will be against what we want to do here.
Apollo Server Fastify is not as fast and feature-rich as mercurious so not sure if we really want to merge this change. Obviously Apollo-server fastify will work as subscription resolvers are in apollo format. Mercurious use graphql-js format and that is why they never worked.

If we think about it sometimes we get stuck with resolving problems and then we use something else. 
In Graphback we follow different ethos. First, we want to know why things do not work and then make the decision to move to something else. 

We wanted to use mercurous. They have subscription examples in their project. 
Do we know why subscriptions do not work with mercurious?

**Comment by RinkiyaKeDad** [comment]
Will get back to you on this

**Comment by wtrocki** [comment]
This is open for a long time. I think we can accept apollo-fastify as exception. Small rebase needed.

**Comment by RinkiyaKeDad** [comment]
Resolved the merge conflict.

**Pull request closed without merging**
