### PR TITLE
chore: add one-to-many resolver to runtime package

### PR DESCRIPTION
**Pull request by b1zzu**
## Description

Implementing missing one-to-many relation in runtime package

### CODE REVIEW

**Comment by jcbdev** [comment]
Believe this is what I need for issue https://github.com/aerogear/graphback/issues/536

couldn't add directly to this PR so opened a new one with the fix for the failed build: https://github.com/aerogear/graphback/pull/537

**Comment by b1zzu** [comment]
Closing this PR in favor of @jcbdev #536 PR

**Comment by wtrocki** [comment]
@b1zzu It is easier to work on PR if branch is upstream. I have reopened this PR and integrated change from other PR.

**Comment by b1zzu** [comment]
@wtrocki I was a little confused, but I got it now

**Comment by wtrocki** [comment]
Blocker until we get migration merged.

**Comment by wtrocki** [comment]
This is back to my list as nr 1 priority

**Pull request merged**
