### PR TITLE
chore(release): bump version to 0.16.1

### PR DESCRIPTION
**Pull request by machi1990**
Also change codegen.yml to .graphqlrc.yml to fix https://github.com/aerogear/graphback/issues/1977

### CODE REVIEW

**Review by craicoverflow — CHANGES_REQUESTED** [review]
I don't see any release notes for 0.16.1, but there was a fix issued in graphql-serve (https://github.com/aerogear/graphback/commit/d4d918e189b9dd03b84d9a8d29194664fe8a898f)

**Comment by machi1990** [comment]
> I don't see any release notes for 0.16.1, but there was a fix issued in graphql-serve ([d4d918e](https://github.com/aerogear/graphback/commit/d4d918e189b9dd03b84d9a8d29194664fe8a898f))

Good point. So this release note will be under the `next` session of the website since `0.16.x` is already in since got me conflicted a little.

**Comment by craicoverflow** [comment]
> Good point. So this release note will be under the next session of the website since 0.16.x is already in since got me conflicted a little.

Unless we rebuild the 0.16 website folder or copy releases.md over.

**Comment by machi1990** [comment]
> > I don't see any release notes for 0.16.1, but there was a fix issued in graphql-serve ([d4d918e](https://github.com/aerogear/graphback/commit/d4d918e189b9dd03b84d9a8d29194664fe8a898f))
> 
> Good point. So this release note will be under the `next` session of the website since `0.16.x` is already in since got me conflicted a little.

I've added  a note under `0.16.x` versioned released note and  `docs/release.md` but modifying in two places is not sustainable.

**Review by craicoverflow — APPROVED** [review]

**Comment by machi1990** [comment]
> > Good point. So this release note will be under the next session of the website since 0.16.x is already in since got me conflicted a little.
> 
> Unless we rebuild the 0.16 website folder or copy releases.md over.

I just copied the content for now since website will be re-built during deploy, I think it should work.

**Pull request merged**
