### PR TITLE
fix(lint): enforce 2-space indent rule

### PR DESCRIPTION
**Pull request by craicoverflow**
There were inconsistencies in indentation in different files. This turns on the ESLint indent rule and sets it to 2, to ensure consistency in all files.

### CODE REVIEW

**Comment by machi1990** [comment]
Thank you.

**Comment by wtrocki** [comment]
Strange to see this happening. Linting probably not picking up 
https://github.com/aerogear/graphback/blob/master/.editorconfig#L14

**Comment by machi1990** [comment]
> Strange to see this happening. Linting probably not picking up
> https://github.com/aerogear/graphback/blob/master/.editorconfig#L14

Worth to mention this in the https://github.com/aerogear/graphback/blob/master/CONTRIBUTING.md ?

**Comment by craicoverflow** [comment]
> Strange to see this happening. Linting probably not picking up
> [/.editorconfig@`master`#L14](https://github.com/aerogear/graphback/blob/master/.editorconfig?rgh-link-date=2020-06-17T16%3A14%3A02Z#L14)

Is ESLint able to use the value in editorconfig? Anyway, it could be something to do with when we migrated from TSLint to ESLint.

**Pull request merged**
