### PR TITLE
more CRUD methods for fullstack template

### PR DESCRIPTION
**Pull request by udith-shalinda**
#691

### CODE REVIEW

**Comment by wtrocki** [comment]
Awesome work! We will need some time to review that carefully!

**Comment by udith-shalinda** [comment]
ok

**Comment by wtrocki** [comment]
Also if you can take look on build and rebase so we can merge that after review

**Comment by wtrocki** [comment]
@udith-shalinda Looks good for me. 
This is very old branch that has some quirks.
Can you rebase that for us and fix conflicts? Thank you so much

**Comment by wtrocki** [comment]
@craicoverflow Any comments?

**Comment by wtrocki** [comment]
What I see here is that this was done based on very old version of the graphback that might not work after rebase.

**Comment by udith-shalinda** [comment]
I'll take a look at it

**Comment by wtrocki** [comment]
@udith-shalinda This made things even worse.
We asked for rebase. Merge created conflicts.

"This branch cannot be rebased due to conflicts" we cannot rebase it and since we were basing on changes from 2 months entire PR needs to be scrapped and recreated from scratch. 

My recomendation:

1. Copy your sample app changes
2. Go to **Latest master**. 
3. Copy back your changes there and review what you push/changed.

Create completely new branch/PR

**Comment by wtrocki** [comment]
Screenshot 2020-03-05 at 15 12 44

**Pull request closed without merging**
