### PR TITLE
website fix

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]

**Comment by machi1990** [comment]
Good catch! Thanks

**Comment by wtrocki** [comment]
i have been talking with some guy about graphback and he said - your init command doesn't even works. I was no way this is tested.

**Comment by wtrocki** [comment]
Today someone else pointed that out... and I was like no way. Upon discussion it happened thst this command was included on website.

**Comment by machi1990** [comment]
> i have been talking with some guy about graphback and he said - your init command doesn't even works. I was no way this is tested and ignored it.

Ah right, that part was not updated once init was moved out graphback-cli. Thank you :-)

**Pull request merged**
