### PR TITLE
update GraphQLResolverCreatorTest snapshots

### PR DESCRIPTION
**Pull request by machi1990**
- Delete phantom snapshots that were generated by Ava
- Update Jest snapshots to take into account latest changes in master. 
- Also explicit set the `trailingComma` to `all` prettier formatting options which seem to be projects default see https://github.com/aerogear/graphback/blob/a8813d451487a91114c51db5ee246fafc0446c07/.prettierrc#L3 

/cc @wtrocki

### CODE REVIEW

**Comment by machi1990** [comment]
> * Delete phantom snapshots that were generated by Ava

Seems like there are couple other files that were generated by Ava and the test runner itself is still there as shown by a quick search on GH https://github.com/aerogear/graphback/search?q=ava&unscoped_q=ava e.g 

Are we using jest or ava or both? 

@wtrocki @craicoverflow

**Comment by machi1990** [comment]
Great, I think we can go ahead and remove all `Ava` references?

**Comment by wtrocki** [comment]
Yes. Anything related to ava should be gone

**Comment by machi1990** [comment]
> Yes. Anything related to ava should be gone

Will prepare a PR some time later today.

**Comment by wtrocki** [comment]
@machi1990 keep it for the week. No need to do boring stuff on weekend

**Pull request merged**
