### PR TITLE
mongodb layer

### PR DESCRIPTION
**Pull request by udith-shalinda**

### CODE REVIEW

**Comment by wtrocki** [comment]
@udith-shalinda Thank you so much for contribution! 
I will need to refine this PR to add a couple things that are missing, but overall work is great! 

I will create separate PR where I will add some changes on top of your commit. You will still have your commits merged, but I need to apply some changes to the PR and github won't let me to edit your branch

**Comment by wtrocki** [comment]
Pro tip. Let's avoid using master in the future

**Comment by udith-shalinda** [comment]
How can I let you edit my branch?

**Comment by wtrocki** [comment]
Closing for https://github.com/aerogear/graphback/pull/746
Please leave that with me :)

**Pull request closed without merging**
