### PR TITLE
chore: add perf data from 1.0.1 release

### PR DESCRIPTION
**Pull request by machi1990**

### CODE REVIEW

**Comment by machi1990** [comment]
After several runs in my computer, the results are relatively the same.

**Comment by machi1990** [comment]
I am going to automatically merge this as its generated anyway. 

/cc @craicoverflow @wtrocki

**Comment by wtrocki** [comment]
Usually, it was also generating photo right?

**Comment by machi1990** [comment]
> Usually, it was also generating photo right?

Nope. We do not have that option. It's just raw data that you can display in a table with `cd performance && yarn compare:stats`

**Comment by wtrocki** [comment]
Ah perfect!

**Pull request merged**
