### PR TITLE
fix: use new runtime api in graphql-serve

### LINKED ISSUE #1448: `printSchemaHandler` still uses GraphbackRuntime
[printSchemaHandler](https://github.com/aerogear/graphback/blob/18b80864290803c7d86736c36e8626de60cbddbd/packages/graphql-serve/src/components/printSchemaHandler.ts#L12) from graphql-serve needs to be updated to use the new runtime API, then we can remove GraphbackRuntime.

When GraphbackRuntime is removed, `LayeredRuntimeResolverCreator` and any related unused files should be removed too.

### PR DESCRIPTION
**Pull request by craicoverflow**
Closes #1448 #1491 

This PR fixes a couple of issues in graphql-serve, and removed LayeredRuntimeResolverCreator which is no longer used.

### Tasks

- [x] Use new runtime API
- [x] Add ability to use Glob pattern
- [x] Add tests for printSchema
- [x] Update docs
- [x] Removed LayeredRuntimeResolverCreator code
- [x] Update CI Node image
- [x] Update release notes

### CODE REVIEW

**Comment by wtrocki** [comment]
I see that you going to resolve numerous issue on one PR. Really excited! thank you

**Comment by machi1990** [comment]
@craicoverflow once this is done, we can safely remove https://github.com/aerogear/graphback/blob/master/packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts?

**Comment by craicoverflow** [comment]
> @craicoverflow once this is done, we can safely remove [/packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts@`master`](https://github.com/aerogear/graphback/blob/master/packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts?rgh-link-date=2020-06-22T10%3A57%3A31Z)?

Yes!

**Comment by wtrocki** [comment]
This is some professional API cleanup. Amazing work. I will go thru this carefully once you mark it as non draft.

**Pull request merged**
