### PR TITLE
Website improvements

### PR DESCRIPTION
**Pull request by wtrocki**
I'm not skilled in layout. Target is to put demo video on the website plus diagram.
While this layout is still quite bad it will give additional value to our users.

Screenshot 2019-08-28 at 13 32 49

### CODE REVIEW

**Comment by wtrocki** [comment]
Actually this was published by mistake: https://graphback.dev/

**Comment by ankitjena** [comment]
> I'm not skilled in layout. Target is to put demo video on the website plus diagram.
> While this layout is still quite bad it will give additional value to our users.

This looks awesome.

**Comment by wtrocki** [comment]
I have noticed that layout on mobile is kinda broken. I will check why

**Comment by darahayes** [comment]
@wtrocki sorry I only got to look at this now. I'm mostly happy with it except the text underneath the Graphback Workflow heading is center aligned which looks pretty bad. Instead it should be left aligned.

**Pull request merged**
