### PR TITLE
fix: Print schema with directives

### PR DESCRIPTION
**Pull request by craicoverflow**
Fixes https://github.com/aerogear/graphback/issues/1089

This fix prints custom directives to the final schema

### CODE REVIEW

**Comment by wtrocki** [comment]
@craicoverflow Strange that we do not have any snapshot for verifying this schema. Would it be possible to add one (SDL string) to see outputs for example model

**Comment by craicoverflow** [comment]
> @craicoverflow Strange that we do not have any snapshot for verifying this schema. Would it be possible to add one (SDL string) to see outputs for example model

Yeah it seems like an important one to have! Of course!

**Comment by craicoverflow** [comment]
@wtrocki there is a snapshot but it did not have any custom directives - and it used `printSchema` this stripping out custom directives. Added in https://github.com/aerogear/graphback/pull/1147/commits/981da21886503f3b11131b303fe2a65c1f61d974

**Comment by wtrocki** [comment]
Perfect

**Pull request merged**
