### PR TITLE
[WIP] fix(schema): prevent overwriting user queries

### PR DESCRIPTION
**Pull request by craicoverflow**
Fix for https://github.com/aerogear/graphback/issues/1656

**This PR is incomplete, requires discussion**

**Description**

The problem is that `buildModel` is called multiple times, so the approach taken here will not work.

The first time `buildModel` is called it is using the original data model schema, which does not have any generated CRUD API yet. At this point it is easy to identify custom queries that have a clashing name. This PR uses this information to update the CRUD options on the ModelDefinition. The main benefit of this is there is a single source of truth for the model's CRUD config.

The next time `buildModel` is called, it is using the schema which has the Graphback queries generated. It sees this as custom user queries and updates the CRUD config accordingly, so no resolvers are created.

The obvious quick solution is to not update the model CRUD config from the custom queries, instead calculating this when needed. The issue I have with this is there are now two truths - The model CRUD config will say that the `create` CRUD is enabled (as an example), but Graphback does not generate this because the user supplied their own custom create query in the schema.

### CODE REVIEW

**Comment by wtrocki** [comment]
I see overriding user queries as feature. If you add model you will be expect some methods to be created. If you create method with the same name (which is unusual) you should probably get validation error?

**Comment by wtrocki** [comment]
Could we document this instead for 0.14.0?

**Comment by craicoverflow** [comment]
Yeah, there is a good discussion over in https://github.com/aerogear/graphback/issues/1656 about this.

This PR is trying to restore the original feature, whereby Graphback did not overwrite custom queries with the same name.

**Comment by craicoverflow** [comment]
Closing as this is documentation issue resolved in #1685

**Pull request closed without merging**
