### PR TITLE
Make schema using opiniated pattersn

### PR DESCRIPTION
**Pull request by ankitjena**
## Input
```
type Note {
  id: ID!
  title: String!
  description: String!
}
```

## Output
```
interface Node {
    id: ID!
}

input NoteFilter {
    id: ID
    title: String
    description: String
}

type PaginationInfo {
    totalPages: Int!
    totalItems: Int!
    page: Int!
    perPage: Int!
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
}

type Note implements Node  {
    id: ID!
    title: String!
    description: String!
}


input NoteInput {
    title: String
    description: String
}

type NotePagination {
    items: [Note]!
    pageInfo: PaginationInfo!
}

type Query {
    findNote(fields: NoteFilter): Note!
    findAllNotes: NotePagination
}

type Mutation {
    createNote(input: NoteInput!): Note!
    updateNote(id: ID!, input: NoteInput!): Note!
    deleteNote(id: ID!): ID!
}

type Subscription {
    newNote: Note!
    updatedNote: Note!
    deletedNote: ID!
}
```
#60

### CODE REVIEW

**Comment by ankitjena** [comment]
@wtrocki so currently what are the things we want to incorporate in building ?
Pagination , Filtering and ?

**Comment by wtrocki** [comment]
Pagination and filtering. Ideally is to let people get their heads around graphql so then they can start writing their own queries and mutations.

**Comment by ankitjena** [comment]
> Pagination and filtering. Ideally is to let people get their heads around graphql so then they can start writing their own queries and mutations.

So what are things we can do here?

**Comment by ankitjena** [comment]
Removed read method, as find and findAll are more reading data.

**Pull request merged**
