### PR TITLE
feat(packages): add a NestJS community template

### LINKED ISSUE #2212: Create Nest.js template
Graphback comes with number of templates (see repo templates directory.) Over the last month we seen increased demand to Nest.js framework and it wil.be good to be able to have some nest.js backend template

### PR DESCRIPTION
**Pull request by namit-chandwani**
Added metadata of a newly created NestJS server template to the `communityTemplates.ts` file.
Fixes #2212

## Types of changes

What types of changes does your code introduce to Graphback?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please specify)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aerogear/graphback/blob/master/CONTRIBUTING.md) document.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by wtrocki** [comment]
Would look into this today. Thank you!

**Comment by wtrocki** [comment]
I have done evaluation of the template itself. 
I think we should at least change it's readme to denote that it is Graphback template.
When this happens we would be able to merge this without issues.

Thank you for amazing job on the template!

**Comment by namit-chandwani** [comment]
I have updated the readme file.
Please have a look now.

**Comment by wtrocki** [comment]
@namit-chandwani Let's work on your repository (there are issues created) and ping me on PR's 
Thx

**Comment by namit-chandwani** [comment]
Yeah sure, I'll start working on them right away.
Will keep you in the loop.

**Comment by namit-chandwani** [comment]
Hey @wtrocki, just came across this old PR.
Can you please review it whenever you're free? TIA

**Review by wtrocki — APPROVED** [review]

**Pull request merged**
