### PR TITLE
fixed typo in the sidebar

### PR DESCRIPTION
**Pull request by apoorvakumar2306**
fixed issue #2127 .

### CODE REVIEW

**Comment by wtrocki** [comment]
Thank you so much Apoorva

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
Checked rendering locally. (for the table changes)

**Review by machi1990 — COMMENTED** [review]
Thanks for the PR. We should also update this https://github.com/aerogear/graphback/blob/430772d4a79ecbcdcb73613d0439e2c699884998/docs/databases/introduction.md file

**Comment by machi1990** [comment]
> Thanks for the PR. We should also update this https://github.com/aerogear/graphback/blob/430772d4a79ecbcdcb73613d0439e2c699884998/docs/databases/introduction.md file

Ignore this comment as this has been already fixed in https://github.com/aerogear/graphback/pull/2128. 

Thanks very much for the PR.

**Comment by apoorvakumar2306** [comment]
@machi1990 I am raising another PR that will fix the issue in the docs.

**Pull request merged**
