### PR TITLE
fix: Separate serve and print-schema Handlers

### PR DESCRIPTION
**Pull request by ssd71**
This PR addresses #864

### CODE REVIEW

**Comment by ssd71** [comment]
#864 is fixed by 90ac933

**Comment by wtrocki** [comment]
Amazing changes.

**Comment by wtrocki** [comment]
Amazing work. This is live and published as graphql-serve@0.10.0

**Comment by wtrocki** [comment]
I have used 0.10.0 to match previous version of the graphback. 0.11.0 will kick in along with the rest of the packages once we do proper release (we use single version for entire stack)

**Pull request merged**
