### PR TITLE
Edited graphback init message

### LINKED ISSUE #2142: Update "Graphback init can create your app from following templates:"
* **Module**: create-graphback
* **Version**: 1.0.1
* **Node.js / npm versions:**

The message "Graphback init can create your app from following templates:" is wrong - `Graphback init` should be replaced with `create-graphback`. Asdditionally, it should be highlighted as a code snippet with `chalk.cyan`.

### PR DESCRIPTION
**Pull request by g-ravity**
- Replaced graphback init with create-graphback
- Added chalk.cyan for code snippet

Fixes #2142

### CODE REVIEW

**Comment by wtrocki** [comment]
@g-ravity Please make PR that changes exactly what was requested. Adding some extra changes will be recorded as spam.

**Comment by g-ravity** [comment]
@wtrocki I haven't added any extra changes. The prettier config for the repo included trailing commas, that's why trailing commas got added to some of the lines when I committed the file.
I'll make the necessary changes and update the PR.

**Comment by wtrocki** [comment]
@g-ravity Yep. That is strange. What editor you using. Have Vscode and not getting this changes. 
Reason for is it that commas are put in places that are really strange and in some cases wroong.

**Comment by g-ravity** [comment]
@wtrocki I just checked, my Format On Save was enabled in VS Code. That's why when I saved the file, it picked up the prettier config and added trailing commas. I turned it off and saved it again. This time the commas were not added.
I'll update the PR with the commas removed, and then squash merge the commits. Then you'll be able to see the actual change

**Comment by wtrocki** [comment]
@g-ravity You can create separate PR to disable those commas. Thank you!

**Review by wtrocki — APPROVED** [review]

**Review by machi1990 — APPROVED** [review]

**Pull request merged**
