### PR TITLE
Port plugins to schemaComposer

### PR DESCRIPTION
**Pull request by ssd71**
WIP
Issue: #810

### CODE REVIEW

**Comment by ssd71** [comment]
I have modified Schema plugin so that it exclusively uses schema composer internally to add to the schema and then converts to immutable schema afterwards and returns that

**Comment by wtrocki** [comment]
Really good work and definitely good path to swap things one by one

**Comment by ssd71** [comment]
Finished with the SchemaPlugin at d27b17e

**Comment by wtrocki** [comment]
It is amazing how simple and easy it was.
@craicoverflow wdyt? Solid merge.for me but will need to test it first

**Comment by craicoverflow** [comment]
> It is amazing how simple and easy it was.
> @craicoverflow wdyt? Solid merge.for me but will need to test it first

I've tested and it works perfect! Great stuff @ssd71

**Pull request merged**
